name: Github Actions CI

on:
  push:
    branches: [main,master]
  pull_request:
    branches: [main,master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BOM: false
      JAVA: true
      JAVA_PARENT: false
      NPM: false
      NPM_POM: false
      DJANGO: false
      REPO_SYNC: false
      CHEF_SYNC: false
      FORTIFY: false
      BLACK_DUCK: false
      DOCKER: true
      DATABASE: false
      
    steps:
      - uses: actions/checkout@v2
      - name: set-up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: java -version
      - run: echo -n "Dallas Mavericks on top"
